# 配置Spring框架的数据源信息
spring:
  application:
    name: qiyu-live-user-provider
  datasource:
    # 设置数据库驱动类名为ShardingSphere驱动
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # 数据库连接URL，使用ShardingSphere连接到qiyu-db-sharding.yml配置的数据库集群
    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yml
    hikari:
      # HikariCP连接池的名称
      pool-name: qiyu-user-pool
      # 连接池最小空闲连接数
      minimum-idle: 15
      # 连接池最大连接数
      maximum-pool-size: 300
      # 连接空闲超时时间（毫秒）
      idle-timeout: 60000
      # 数据库连接初始化SQL
#      connection-init-sql: SELECT 1
      # 等待新连接的最大毫秒数
      connection-timeout: 4000
      # 连接的最大生命周期（毫秒）
      max-lifetime: 60000
  data:
    redis:
      host: 123.60.49.130
      port: 6379
      password: redis_1120
      lettuce:
        pool:
          max-active: 1000
          max-idle: 100
          min-idle: 10

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://123.60.49.130:8848?namespace=qiyu-live-test
  server: true
  protocol:
    name: dubbo
    port: 9090

# 配置RocketMQ消息服务的相关参数
qiyu:
  rmq:
    producer:
      # 指定Name Server的地址
      nameSrv: 123.60.49.130:9876
      # 生产者组名，这里动态引用了Spring应用的名字
      groupName: ${spring.application.name}
      # 设置消息发送失败后的重试次数
      retryTimes: 3
      # 设置消息发送的超时时间
      sendTimeOut: 3000
    consumer:
      # 指定Name Server的地址，用于消费者连接
      nameSrv: 123.60.49.130:9876
      # 消费者组名，这里动态引用了Spring应用的名字
      groupName: ${spring.application.name}
