spring:
  application:
    name: qiyu-live-id-generate-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.49.130:3306/qiyu_live_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql_1120
    idle-timeout: 5  # 空闲超时时间，单位：分钟
    minimum-idle: 100  # 最小空闲连接数
    maximum-pool-size: 1000  # 最大连接池大小
    connection-timeout: 60000  # 连接超时时间，单位：毫秒（增加到 60 秒）

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://123.60.49.130:8848
    protocol:
      name: dubbo
      port: 9098